title: Collection Configuration
description: Configuration for a MongoDB collection's version history and migrations
type: object
properties:
  name:
    description: The name of the MongoDB collection
    type: word
  versions:
    description: List of version configurations in chronological order
    type: array
    items:
      type: object
      description: Configuration for a specific version
      properties:
        version:
          description: Version string in format major.minor.patch.schema
          type: version4
        testData:
          description: Name of the test data file for this version
          type: word
        addIndexes:
          description: List of indexes to add in this version
          type: array
          items:
            description: MongoDB index configuration
            type: object
            properties:
              name:
                description: Name of the index
                type: word
              key:
                description: Index key specification
                type: object
              options:
                description: MongoDB index options
                type: object
        dropIndexes:
          description: List of index names to drop in this version
          type: array
          items:
            type: word
        aggregations:
          description: List of aggregation pipelines to run for this version
          type: array
          items:
            description: MongoDB aggregation pipeline stages
            type: array 